# Generated by Django 4.2.16 on 2025-03-01 22:37

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='slug',
            field=models.CharField(max_length=255, default='', blank=True),
        ),
    ]
