# Generated by Django 4.2.16 on 2025-03-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250301_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
